package providers

import "testing"

func TestCleanTitleRemovesWrapperBlocks(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "local-command-caveat 整块删除",
			in: "<local-command-caveat>Caveat: The messages below were generated by the user " +
				"while running local commands. DO NOT respond to these messages.</local-command-caveat>",
			want: "",
		},
		{
			name: "斜杠命令回显整块删除",
			in: "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n" +
				"<command-args></command-args>",
			want: "",
		},
		{
			name: "包装块后跟真实提问",
			in: "<system-reminder>今天日期 2026-09-28</system-reminder>\n帮我把登录页的报错文案改一下",
			want: "帮我把登录页的报错文案改一下",
		},
		{
			name: "只包着正文的标签保留内容",
			in: "<user_query>继续对界面进行美化</user_query>",
			want: "继续对界面进行美化",
		},
		{
			name: "嵌套包装块（additional_data 里嵌 rules）",
			in: "<user_info>some info</user_info><additional_data>ctx\n<rules>r1</rules>\n</additional_data>" +
				"<user_query>做卡片布局</user_query>",
			want: "做卡片布局",
		},
		{
			name: "附件清单整块删除",
			in: "<manually_attached_skills>name: using-superpowers\ndescription: x</manually_attached_skills>\n" +
				"<external_links>https://example.com</external_links>",
			want: "",
		},
		{
			// 头部读取有长度上限，长包装块被截断是常态：开头的未闭合包装标签 => 整段丢弃
			name: "开头未闭合的包装块整段丢弃",
			in:   "<system-reminder>注意这里是被截断的机器上下文",
			want: "",
		},
		{
			// 包装正文的标签不在丢弃列表里，被截断时内容仍应保留
			name: "开头未闭合的 user_query 保留正文",
			in:   "<command-args>把工作区做成卡片",
			want: "把工作区做成卡片",
		},
		{
			name: "标签名相近但不相同不算包装标签",
			in:   "<rulesfoo>正文",
			want: "<rulesfoo>正文",
		},
		{
			name: "普通文本原样折叠空白",
			in: "  修复   上传白名单\n校验 ",
			want: "修复 上传白名单 校验",
		},
		{
			name: "空输入",
			in:   "",
			want: "",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := cleanTitle(tc.in); got != tc.want {
				t.Fatalf("cleanTitle(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// 用户正文里出现的尖括号内容不该被当成标签吃掉（只删已知标签）。
func TestCleanTitleKeepsUnknownAngleBrackets(t *testing.T) {
	in := "把 <Foo> 组件改成 <Bar>"
	if got := cleanTitle(in); got != in {
		t.Fatalf("cleanTitle(%q) = %q, want unchanged", in, got)
	}
}
