// 终端窗口标题归一化测试：与 Go 侧 WindowManager.TerminalTitle 的行为逐条对齐。
import { describe, expect, it } from 'vitest';
import { displayTitle, terminalTitle } from './title';

describe('terminalTitle', () => {
  it('短标题加前缀，不截断', () => {
    expect(terminalTitle('修复上传白名单')).toBe('kshell · 修复上传白名单');
  });

  it('超 80 rune 截到 79 rune 并补省略号', () => {
    const title = '长'.repeat(100); // "kshell · " 占 9 rune，总长 109
    const result = terminalTitle(title);
    expect(Array.from(result)).toHaveLength(80);
    expect(result.endsWith('…')).toBe(true);
    expect(result.startsWith('kshell · ')).toBe(true);
  });

  it('恰好 80 rune 不截断、无省略号', () => {
    const title = 'x'.repeat(71); // 9 + 71 = 80
    const result = terminalTitle(title);
    expect(Array.from(result)).toHaveLength(80);
    expect(result.endsWith('…')).toBe(false);
  });

  it('按 rune 而非字节截断（中文与 emoji 同为一 rune）', () => {
    const title = '🚀'.repeat(100); // 每个 emoji 是 2 个 UTF-16 码元、1 个 rune
    const result = terminalTitle(title);
    expect(Array.from(result)).toHaveLength(80);
    // 截断必须落在 emoji 边界上：结尾是完整的 emoji + 省略号，不产生孤立代理对
    expect(result.endsWith('🚀…')).toBe(true);
  });
});

// displayTitle 与 Go 侧 internal/providers/title.go 的 cleanTitle 同源，
// 用例与 internal/providers/title_test.go 逐条对应（历史数据 / 未重扫的缓存兜底）。
describe('displayTitle', () => {
  it('整块删除机器注入的包装标签（含内容）', () => {
    expect(
      displayTitle(
        '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>',
      ),
    ).toBe('');
  });

  it('斜杠命令回显整块删除', () => {
    expect(
      displayTitle(
        '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>',
      ),
    ).toBe('');
  });

  it('包装块后跟真实提问：只留提问', () => {
    expect(
      displayTitle(
        '<system-reminder>今天日期 2026-09-28</system-reminder>\n帮我把登录页的报错文案改一下',
      ),
    ).toBe('帮我把登录页的报错文案改一下');
  });

  it('<user_query> / <user_message> / <command-args> 只删标记保留正文', () => {
    expect(displayTitle('<user_query>  继续对界面进行美化  </user_query>')).toBe(
      '继续对界面进行美化',
    );
    expect(displayTitle('<user_message>重构登录页</user_message>')).toBe('重构登录页');
  });

  it('嵌套包装块（additional_data 里嵌 rules）循环删干净', () => {
    expect(
      displayTitle(
        '<user_info>some info</user_info><additional_data>ctx\n<rules>r1</rules>\n</additional_data><user_query>做卡片布局</user_query>',
      ),
    ).toBe('做卡片布局');
  });

  it('附件清单整块删除', () => {
    expect(
      displayTitle(
        '<manually_attached_skills>name: using-superpowers\ndescription: x</manually_attached_skills>\n<external_links>https://example.com</external_links>',
      ),
    ).toBe('');
  });

  it('开头未闭合的包装块（头部被截断）整段丢弃', () => {
    expect(displayTitle('<system-reminder>注意这里是被截断的机器上下文')).toBe('');
    expect(displayTitle('  <timestamp>2026-09-28T10:00:00Z')).toBe('');
  });

  it('开头未闭合的 user_query / command-args 保留正文', () => {
    expect(displayTitle('<command-args>把工作区做成卡片')).toBe('把工作区做成卡片');
    expect(displayTitle('<user_query>给会话列表加过滤')).toBe('给会话列表加过滤');
  });

  it('标签名相近但不相同不算包装标签（<rulesfoo> 不误伤）', () => {
    expect(displayTitle('<rulesfoo>正文</rulesfoo>')).toBe('<rulesfoo>正文</rulesfoo>');
  });

  it('大小写不敏感，容错属性与换行', () => {
    expect(displayTitle('<SYSTEM-REMINDER a="1">\n提示\n</SYSTEM-REMINDER>真实标题')).toBe(
      '真实标题',
    );
  });

  it('普通文本原样折叠空白', () => {
    expect(displayTitle('  修复   上传白名单\n校验 ')).toBe('修复 上传白名单 校验');
  });

  it('OSC 调色板/背景色应答残片整段丢弃', () => {
    expect(displayTitle('4;0;rgb:2e2e/3434/3636')).toBe('');
    expect(displayTitle('11;rgb:2e2e/3434/3636')).toBe('');
  });

  it('空输入 / 纯空白返回空串（调用方据此显示「无标题」）', () => {
    expect(displayTitle('')).toBe('');
    expect(displayTitle(' \n\t ')).toBe('');
  });
});
